In [4]:
import numpy as np
# ^^^ pyforest auto-imports - don't write above this line
import numpy as np

## Nunmpy array

- Vector

In [5]:
my_list = [1,2,3,4,67,8,9,4,22,2,4,44]

In [6]:
my_list * 2

[1, 2, 3, 4, 67, 8, 9, 4, 22, 2, 4, 44, 1, 2, 3, 4, 67, 8, 9, 4, 22, 2, 4, 44]

In [7]:
my_list > 5

TypeError: '>' not supported between instances of 'list' and 'int'

## Convert list to numpy array

In [8]:
my_array = np.array(my_list)

In [9]:
my_array

array([ 1,  2,  3,  4, 67,  8,  9,  4, 22,  2,  4, 44])

In [10]:
type(my_array)

numpy.ndarray

In [11]:
my_array.size

12

In [12]:
my_array.shape

(12,)

In [13]:
test1 =[[1],
        [2],
        [3],
        [4]]

In [14]:
len(np.array(test1).shape)

2

In [15]:
np.random.random(size=(12,))

array([0.66483682, 0.13489006, 0.58344099, 0.30715895, 0.26089048,
       0.73101849, 0.9766017 , 0.25500904, 0.36668647, 0.70064604,
       0.87250869, 0.76864869])

In [16]:
# 1-D
len(my_array.shape)

1

In [17]:
# 2-D
len((6,3))

2

In [18]:
my_array * 2

array([  2,   4,   6,   8, 134,  16,  18,   8,  44,   4,   8,  88])

In [19]:
my_array

array([ 1,  2,  3,  4, 67,  8,  9,  4, 22,  2,  4, 44])

In [20]:
my_array > 5

array([False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True])

In [21]:
condition = my_array > 5

In [22]:
condition

array([False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True])

In [23]:
my_list_of_lists = [[1,2,3],
                   [4,5,6]]

In [24]:
np.array(my_list_of_lists)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.array(my_list_of_lists).shape

(2, 3)

In [26]:
my_matrix = np.array(my_list_of_lists)

In [27]:
my_matrix[1,1]

5

In [28]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
my_matrix[:,1]

array([2, 5])

In [30]:
my_matrix[1,:]

array([4, 5, 6])

In [59]:
my_matrix = np.random.randint(low=2, high=20, size=(4,6))
my_matrix

array([[ 2,  4,  4, 11, 15, 11],
       [12,  9,  5, 16,  9,  9],
       [ 9,  3,  6, 18, 14, 14],
       [ 9,  5, 14, 14, 19, 19]])

In [32]:
my_matrix[2,0] = np.mean(my_matrix)

In [33]:
my_matrix

array([[ 4, 11, 19, 14, 19,  6],
       [ 6, 13,  3, 17, 17,  3],
       [11,  5, 14, 18, 13, 16],
       [ 6, 13,  4,  9,  6, 14]])

In [39]:
my_matrix.shape

(4, 6)

In [41]:
nrows = my_matrix.shape[0]
ncolumns = my_matrix.shape[1]

In [46]:
my_matrix

array([[ 4, 11, 19, 14, 19,  6],
       [ 6, 13,  3, 17, 17,  3],
       [11,  5, 14, 18, 13, 16],
       [ 6, 13,  4,  9,  6, 14]])

In [50]:
my_list = [1,2,3]

In [51]:
my_list[0] = 100

In [52]:
my_list

[100, 2, 3]

In [55]:
another_matrix = np.empty(my_matrix.shape)

In [56]:
another_matrix

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90104239e-307, 1.02359984e-306, 1.60218491e-306],
       [1.69119330e-306, 1.42419802e-306, 1.60220936e-306,
        1.95820216e-306, 1.37962320e-306, 8.45593934e-307],
       [1.78019761e-306, 8.90071984e-308, 8.45590538e-307,
        1.69121231e-306, 2.04719290e-306, 1.00137406e-307],
       [2.78150360e-307, 1.37962320e-306, 1.33511018e-306,
        6.23059726e-307, 1.86921958e-306, 2.22522596e-306]])

In [60]:
my_matrix

array([[ 2,  4,  4, 11, 15, 11],
       [12,  9,  5, 16,  9,  9],
       [ 9,  3,  6, 18, 14, 14],
       [ 9,  5, 14, 14, 19, 19]])

In [65]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
np.split(np.arange(8), indices_or_sections=2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [78]:
x = np.random.randint(0, 10, (3,4))

In [79]:
x

array([[4, 8, 5, 3],
       [9, 4, 9, 8],
       [1, 3, 6, 5]])

In [103]:
np.split(x, indices_or_sections=(2,), axis=1 )

[array([[4, 8],
        [9, 4],
        [1, 3]]),
 array([[5, 3],
        [9, 8],
        [6, 5]])]

In [64]:
for row_number in range(nrows):
    for col_number in range(ncolumns):
        print(row_number, col_number, my_matrix[row_number, col_number])

0 0 2
0 1 4
0 2 4
0 3 11
0 4 15
0 5 11
1 0 12
1 1 9
1 2 5
1 3 16
1 4 9
1 5 9
2 0 9
2 1 3
2 2 6
2 3 18
2 4 14
2 5 14
3 0 9
3 1 5
3 2 14
3 3 14
3 4 19
3 5 19


In [61]:
for i in range(nrows):
    for j in range(ncolumns):
        
        if my_matrix[i,j] > 0 and my_matrix[i,j] < 5:
            another_matrix[i,j] = 100

In [62]:
another_matrix

array([[1.00000000e+002, 1.00000000e+002, 1.00000000e+002,
        8.90104239e-307, 1.02359984e-306, 1.60218491e-306],
       [1.69119330e-306, 1.42419802e-306, 1.60220936e-306,
        1.95820216e-306, 1.37962320e-306, 8.45593934e-307],
       [1.78019761e-306, 1.00000000e+002, 8.45590538e-307,
        1.69121231e-306, 2.04719290e-306, 1.00137406e-307],
       [2.78150360e-307, 1.37962320e-306, 1.33511018e-306,
        6.23059726e-307, 1.86921958e-306, 2.22522596e-306]])

In [54]:
my_matrix

array([[100,  11,  19,  14,  19,   6],
       [  6,  13, 100,  17,  17, 100],
       [ 11,   5,  14,  18,  13,  16],
       [  6,  13, 100,   9,   6,  14]])

In [58]:
nrows = my_matrix.shape[0]
ncolumns = my_matrix.shape[1]

for row_number in range(nrows):
    for col_number in range(ncolumns):
        if my_matrix[row_number, col_number] > 5:
            print(f'Trocando {my_matrix[row_number, col_number]} na posicao {row_number}, {col_number} para 20')
            my_matrix[row_number, col_number] = 20

        print(row_number, col_number, my_matrix[row_number, col_number])

0 0 0
0 1 0
0 2 0
Trocando 9 na posicao 0, 3 para 20
0 3 20
Trocando 9 na posicao 0, 4 para 20
0 4 20
0 5 2
Trocando 6 na posicao 1, 0 para 20
1 0 20
1 1 2
1 2 0
1 3 5
1 4 2
1 5 4
2 0 5
2 1 4
2 2 5
2 3 0
Trocando 9 na posicao 2, 4 para 20
2 4 20
Trocando 8 na posicao 2, 5 para 20
2 5 20
3 0 4
Trocando 9 na posicao 3, 1 para 20
3 1 20
3 2 4
3 3 4
Trocando 8 na posicao 3, 4 para 20
3 4 20
3 5 5


In [57]:
my_matrix

array([[0, 0, 0, 9, 9, 2],
       [6, 2, 0, 5, 2, 4],
       [5, 4, 5, 0, 9, 8],
       [4, 9, 4, 4, 8, 5]])

In [59]:
my_matrix

array([[ 0,  0,  0, 20, 20,  2],
       [20,  2,  0,  5,  2,  4],
       [ 5,  4,  5,  0, 20, 20],
       [ 4, 20,  4,  4, 20,  5]])